title: Tejashree Kulkarni
logo: Portfolio_pic.jpg
description: Newly-minted techie with an obsession for taming circuits â€“ packing just enough design verification and ASIC savvy to dive deep and still ask way too many questions!
theme: jekyll-theme-minimal
email: tkulkar@ncsu.edu
